config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'pages#dashboard', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :users do
    resources :customers
    resources :invoices
    resources :parts
  end

end

app/views/shared/_flashes.html.erb
<div style="margin-left: 230px;">
  <% if notice %>
    <div class="alert alert-dismissible text-center flashes" role="alert" id="notices">
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-dismissible text-center flashes" role="alert" id="alerts">
      <%= alert %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-wagon" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="text-center padding-top-row">
            <%= image_tag "http://placehold.it/70x70", class: "img-avatar" %>
          </li>
          <li class="padding-bottom-row">
            <%= link_to edit_user_registration_path, id: "link-profile-section" do %>
              <%= current_user.first_name %>
            <% end %>
          </li>
          <li>
            <%= link_to "Créer une facture", new_users_invoice_path, class: "btn", id: "btn-navbar-new-invoice" %>
          </li>
          <li>
            <%= link_to authenticated_root_path do %>
              <i class="fa fa-tachometer"></i> Tableau de bord
            <% end %>
          </li>
          <li>
            <%= link_to users_invoices_path do %>
              <i class="fa fa-file-text-o"></i> Factures
            <% end %>
          </li>
          <li>
            <%= link_to '#' do %>
              <i class="fa fa-file-o"></i> Devis
            <% end %>
          </li>
          <li>
            <%= link_to users_customers_path do %>
              <i class="fa fa-users"></i> Clients
            <% end %>
          </li>
          <li>
            <%= link_to users_parts_path do %>
              <i class="fa fa-car"></i> Pièces
            <% end %>
          </li>
          <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  Se déconnecter
          <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to "S'inscrire", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "Se connecter", new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>