config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'pages#dashboard', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :users do
    resources :customers
    resources :invoices
    resources :parts
  end

end

app/views/pages/dashboard.html.erb
<div class="container">
  <div id="page-wrapper">
      <div id="page-inner">
          <div class="row">
              <div class="col-md-12">
                  <h1 class="page-header">
                      Tableau de bord - <%= current_user.first_name %>
                  </h1>
              </div>
          </div>
          <!-- /. ROW  -->

          <div class="row">
              <div class="col-md-3 col-sm-12 col-xs-12 small-side-padding">
                  <div class="panel panel-primary text-center no-boder bg-color-red">
                      <div class="panel-body">
                          <i class="fa fa-file-text-o fa-5x"></i>
                          <h3><%= @monthly_invoices.length %></h3>
                      </div>
                      <div class="panel-footer back-footer-red">
                          Factures (<%= l(Date.today, format: :only_month_name).capitalize %>)
                      </div>
                  </div>
              </div>
              <div class="col-md-3 col-sm-12 col-xs-12 small-side-padding">
                  <div class="panel panel-primary text-center no-boder bg-color-blue">
                      <div class="panel-body">
                          <i class="fa fa-money fa-5x"></i>
                          <h3><%= @monthly_ca %> €</h3>
                      </div>
                      <div class="panel-footer back-footer-blue">
                          Chifrre d'affaires (<%= l(Date.today, format: :only_month_name).capitalize %>)
                      </div>
                  </div>
              </div>
              <div class="col-md-3 col-sm-12 col-xs-12 small-side-padding">
                  <div class="panel panel-primary text-center no-boder bg-color-green">
                      <div class="panel-body">
                          <i class="fa fa fa-line-chart fa-5x"></i>
                          <h3><%= @monthly_net_profit %> €</h3>
                      </div>
                      <div class="panel-footer back-footer-green">
                          Revenu net (<%= l(Date.today, format: :only_month_name).capitalize %>)

                      </div>
                  </div>
              </div>
              <div class="col-md-3 col-sm-12 col-xs-12 small-side-padding">
                  <div class="panel panel-primary text-center no-boder bg-color-brown">
                      <div class="panel-body">
                          <i class="fa fa-bar-chart-o fa-5x"></i>
                          <h3><%= @monthly_mo_hours.round(2) %>h </h3>
                      </div>
                      <div class="panel-footer back-footer-brown">
                          Heures facturées (<%= l(Date.today, format: :only_month_name).capitalize %>)

                      </div>
                  </div>
              </div>
          </div>

          <div class="row">
              <div class="col-xs-12">
                  <div class="panel panel-default">
                      <div class="panel-heading">
                          <h3>Dernières factures</h3>
                      </div>
                      <div class="panel-body">
                          <div class="list-group">
                              <% @invoices_five_last.each do |invoice| %>
                                <%= link_to users_invoice_path(invoice), class: "list-group-item" do %>

                                  <div style="float: left; width: auto; padding: 0px 10px 0px 0px">
                                    n°<%= invoice.id %>
                                  </div>
                                  <div style="width: 25%; float: left;">
                                    <i class="fa fa-fw fa-user"></i> <%= invoice.customer.first_name %> <%= invoice.customer.last_name %>
                                  </div>
                                    <i class="fa fa-fw fa-wrench"></i> <%= invoice.description_mo.first(50) %>
                                    <span class="badge"><%= invoice.total_price %> €</span>
                                <% end %>
                              <% end %>
                          </div>
                          <div class="text-right">
                              <%= link_to users_invoices_path do %>
                              Toutes les factures <i class="fa fa-arrow-circle-right"></i>
                              <% end %>
                          </div>
                      </div>
                  </div>

              </div>
              <div class="col-xs-12">

                  <div class="panel panel-default">
                      <div class="panel-heading">
                          <h3>Bilan de l'année <%= Date.today.year %></h3>
                      </div>
                      <div class="panel-body text-center">
                          <div class="table-responsive">
                              <table class="table table-striped table-bordered table-hover">
                                  <thead class="th-center thead-ca">
                                      <tr>
                                          <th>Mois</th>
                                          <th>Factures</th>
                                          <th>Chiffre d'affaires</th>
                                          <th>Heures de travail</th>
                                          <th>Revenu net pièces</th>
                                          <th>Revenu net m.o</th>
                                          <th>Revenu net total</th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                      <% @year_balance_elements.each_with_index do |element, index| %>
                                        <tr>
                                            <td><%= l(Date.new(2015, index + 1), format: :only_month_name).capitalize %></td>
                                            <td><%= element[:monthly_invoices] %></td>
                                            <td><%= element[:monthly_ca] %> €</td>
                                            <td><%= element[:monthly_mo_hours] %></td>
                                            <td><%= element[:monthly_net_profit_parts] %> €</td>
                                            <td><%= element[:monthly_net_profit_mo] %> €</td>
                                            <td><%= element[:monthly_net_profit_total] %> €</td>
                                        </tr>
                                      <% end %>
                                  </tbody>
                              </table>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="col-xs-12">
                  <div class="panel panel-default">
                      <div class="panel-heading">
                          <h3>Charges sociales de l'année <%= Date.today.year %>*</h3>
                      </div>
                      <div class="panel-body text-center">
                          <div class="table-responsive">
                              <table class="table table-striped table-bordered table-hover">
                                  <thead class="th-center thead-charges">
                                      <tr>
                                          <th>Mois</th>
                                          <th>CA</th>
                                          <th>Charges main-d'oeuvre</th>
                                          <th>Charges pièces</th>
                                          <th>Charges total</th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                      <% @year_charges_elements.each_with_index do |element, index| %>
                                        <tr>
                                            <td><%= l(Date.new(2015, index + 1), format: :only_month_name).capitalize %></td>
                                            <td><%= element[:monthly_ca] %> €</td>
                                            <td><%= element[:monthly_charges_social_mo] %> €</td>
                                            <td><%= element[:monthly_charges_social_parts] %> €</td>
                                            <td><%= element[:monthly_charges_social_total] %> €</td>
                                        </tr>
                                      <% end %>
                                  </tbody>
                              </table>
                              <p class='text-left'><i>*Main-d'oeuvre : 22.9% - Pièces : 20.0%</i></p>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div><!-- /. PAGE INNER  -->
  </div>
</div>